### ISSUE TITLE
Add matcher aliases for composability

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-collection_matchers#23]
While I think that the simplicity of `expect(collection.size).to eq(3)` is often preferrable to these matchers, particularly for users who don't already understand them, there is one really nice advantage these matchers have: they can be composed, supporting things like:

``` ruby
expect(collection).to have(3).items.and all( match(:name => String))
```

It reads well there but reads less well when passing it as an argument to another matcher, such as:

``` ruby
expect { |probe|
  foo.bar(&probe)
}.to yield_with_args( have(3).items )
```

In rspec-expectations we've provided aliases for the built in matchers that use a noun-phrase for the matcher so that they read better for this kind of situation.  Following the conventions there, we would use an `a_collection_having` as an alias for `have`, so that you could use:

``` ruby
expect { |probe|
  foo.bar(&probe)
}.to yield_with_args( a_collection_having(3).items )
```

Users can define this alias on their own with `RSpec::Matchers.alias_matcher` but it would be nice if this gem defined these sorts of aliases automatically.  Thoughts?

**Comment by JonRowe** [comment]
Closing as not planned
