### ISSUE TITLE
errors_on with custom :on argument

### ISSUE THREAD

**Issue by linkyndy** [rspec/rspec-collection_matchers#30]
Is it possible somehow to do something like this?

```
expect(obj).to have(:no).errors_on(:field, on: :create)
```

I would need to run only the validations that specify the given `:on` argument.

**Comment by JonRowe** [comment]
Did you try `expect(model).to have(:no).errors_on(:field, :context => :create)`?

**Comment by linkyndy** [comment]
Indeed, that's working! Thanks.
