### ISSUE TITLE
Errors_on is empty while errors[:key] is present

### ISSUE THREAD

**Issue by ivanovaleksey** [rspec/rspec-collection_matchers#32]
Hi.

I got test like
```
it 'should have errors' do
  expect(order).to have(1).errors_on :reserved_at
end
```

But it always fails saying
```
     Failure/Error: expect(order).to have(1).errors_on :reserved_at }
       expected 1 errors on :reserved_at, got 0
```

Though if I add some `puts` it shows that error is present
```
it 'should have errors' do
  puts order.errors[:reserved_at] # => ["must be blank"]
  expect(order).to have(1).errors_on :reserved_at
end
```

I am using
```
rspec-rails (3.4.2)
rspec-collection_matchers (1.1.2)
```

Could someone help me to figure it out?

Thank you.

**Comment by JonRowe** [comment]
This does look like a bug, `rspec-collection-matchers` isn't actively maintained by the rspec team, but I'll try to help, what does `order.errors_on :reserved_at` return? the `errors_on` method is mixed into activemodel::validations so should be available on your object.

**Comment by ivanovaleksey** [comment]
@JonRowe Thank you for the help.
`have(...).errors_on` expectations are not always failed. I have another specs (even very similar ones, with just different `context`) which pass fine.

I already tried to debug what `order.errors_on :reserved_at` is. It is empty.
In specs where `have(...).errors_on` is working `order.errors_on :reserved_at` returns an array like `['some error message']`.

I have noticed one thing. 
In my `Order` model I have validation
```
def check_reserved_at
  errors.add(:reserved_at, :present) if reserved? && !can_be_reserved?
  errors.add(:reserved_at, :blank) if !reserved? && !can_remove_reserve?
  p errors
  # => #<ActiveModel::Errors:0x007fbaf44ff0e0 @base=#<Order id: nil, customer_id: 1, ..., reserved_at: nil>,
          @messages={:reserved_at=>["can't be blank"]}>
end
```
Notice that there is error message here.

But in my spec
```
it 'should have errors' do
  p order.errors_on :reserved_at # => []
  p order.errors[:reserved_at] # => []
  p order.errors
  # => #<ActiveModel::Errors:0x007fbaf44ff0e0 @base=#<Order id: nil, customer_id: 1, ..., reserved_at: nil>,
          @messages={:reserved_at=>[]}>

  expect(order).to have(1).errors_on :reserved_at
end
```
Errors message is gone. 😶

**Comment by JonRowe** [comment]
The `have(n).errors_on(...)` matcher triggers `valid?` so you need to make sure your errors are still present after a valid call to use the matcher.

**Comment by ivanovaleksey** [comment]
I feel such a fool. I completely forgot about `valid?` call.
In my case `valid?` returns `true` because in `Order` model I have `if` on validation

`validate  :check_reserved_at, if: :reserved_at_changed?`

And `check_reserved_at` was not even called.
Thank you so much Jon!
