### ISSUE TITLE
cucumber test suite failures

### ISSUE THREAD

**Issue by pvalena** [rspec/rspec-collection_matchers#51]
Cucumber test suite is failing:

```
Failing Scenarios:
cucumber features/have.feature:32 # Scenario: have(x).items on a collection
cucumber features/have.feature:70 # Scenario: have(x).words on a String when String#words is defined
```
Full log: https://gist.github.com/pvalena/2b3a60893344239c5994d41cdbefa002

I'm executing this as part of Fedora package build. This has worked previously, so is probably dependant on update cucumber version.

Cucumber versions:
```
 rubygem-cucumber                        noarch  7.1.0-6.fc39           fedora     113 k
 rubygem-cucumber-core                   noarch  10.1.0-5.fc39          fedora      34 k
 rubygem-cucumber-create-meta            noarch  6.0.4-1.fc39           copr_base   13 k
 rubygem-cucumber-cucumber-expressions   noarch  14.0.0-5.fc39          fedora      26 k
 rubygem-cucumber-gherkin                noarch  22.0.0-5.fc39          fedora      39 k
 rubygem-cucumber-messages               noarch  22.0.0-1.fc39          copr_base   24 k
 rubygem-cucumber-tag-expressions        noarch  4.0.2-5.fc39           fedora      11 k
 rubygem-cucumber-wire                   noarch  6.2.1-1.fc39~bootstrap copr_base   17 k

```
Full list: https://gist.github.com/pvalena/447dd83d45e68b6dada9834c4b32a752

**Comment by JonRowe** [comment]
If it worked before I suggest rolling back to the previous version of cucumber, unless you'd like to fix them in a PR

**Comment by pvalena** [comment]
The Fedora OS never downgrades versions. Also, your gem is the only one breaking compatibility - currently removed from the system - so I'm just reporting the issue.

**Comment by JonRowe** [comment]
This gem was extracted from the core rspec gems for back compatibility, its test suite is compatible with an older version of cucumber when it was written and the core team has no bandwidth to maintain it currently, closing as "not planned" but if someone wants to tackle upgrading the suite we'd review a PR.
